# バージョン情報
version: 2 # カスタム機能を利用するためにバージョン2を指定

# ----------------------------------------------------
# 1. AIへの指示（プロンプト）
#    AIのレビュー観点、トーン、コメント形式をここで定義します。
# ----------------------------------------------------
prompt: |
  あなたは経験豊富なシニアエンジニアです。以下のガイドラインに従って、
  Pull Requestの差分とその周辺コードに焦点を当ててレビューを行ってください。

  ## レビュー観点
  1. **スコープ:** PRの変更点に直接関連するコードのみをレビューし、無関係な既存のバグや問題は指摘しないでください。
  2. **プロジェクト固有ルール:** レビュー時は、このリポジトリ固有の[コードレビュー規則](.kiro/steering/code-review-rules.md)を厳密に参照し、違反がないかを確認してください。
  3. **コメントのトーン:** - 建設的で具体的なフィードバックを提供してください。
     - 改善案は、具体的なコード例（差分形式など）と共に提示してください。

  ## 問題の分類と形式
  発見した問題は、以下の重大度を明記し、簡潔に分類してください。
  * **🔴 Critical:** 必須対応（FSD違反、セキュリティ問題、システム障害につながる問題）
  * **🟡 Warning:** 推奨対応（コーディング規約違反、パフォーマンス懸念、保守性の問題）
  * **🟢 Good:** 良い実装を積極的に評価してください。

  レビュー結果は、差分行に対するインラインコメントとして投稿してください。
  
# ----------------------------------------------------
# 2. 外部ルールドキュメントの参照
#    プロジェクト固有のコードレビュー規則をAIに提供します。
# ----------------------------------------------------
rules:
  # ファイルパスの指定
  - path: .kiro/steering/code-review-rules.md
    # AIがこのファイルをどう扱うかを指示
    description: "このプロジェクトの公式なコードレビュー規則です。レビュー時に必ず参照してください。"
    type: "document" # ドキュメントとして参照させる

# ----------------------------------------------------
# 3. レビュー対象外の設定 (任意)
#    レビューコストの削減とノイズの除去
# ----------------------------------------------------
exclude_paths:
  - 'package-lock.json'
  - 'yarn.lock'
  - 'dist/*'
  - 'vendor/*'
  - '**/*.md'

reviews:
  review_status: "complete"
  incremental_review: false